DROP TABLE IF EXISTS items CASCADE;

CREATE TABLE items(
  id SERIAL PRIMARY KEY,
  items VARCHAR(255) NOT NULL,
  checked BOOLEAN DEFAULT false, 
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);